# Memoria que Gradle puede usar al compilar. Si tu PC tiene poca RAM, baja este numero.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Compila modulos en paralelo (mas rapido).
org.gradle.parallel=true

# Usar las librerias modernas AndroidX (obligatorio en proyectos nuevos).
android.useAndroidX=true

# Estilo de codigo oficial de Kotlin.
kotlin.code.style=official

# Cada modulo genera solo SUS recursos en la clase R (compilacion mas rapida).
android.nonTransitiveRClass=true
